// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.LnVps
{
    [LnVpsResourceType("LnVps:index:CustomVM")]
    public partial class CustomVM : global::Pulumi.CustomResource
    {
        /// <summary>
        /// VM IP addresses.
        /// </summary>
        [Output("ip_assignments")]
        public Output<ImmutableArray<string>> IpAssignments { get; private set; } = null!;

        /// <summary>
        /// ID of SSH key installed on VM.
        /// </summary>
        [Output("ssh_key_id")]
        public Output<string?> SshKeyId { get; private set; } = null!;

        /// <summary>
        /// VM status.
        /// </summary>
        [Output("status")]
        public Output<string?> Status { get; private set; } = null!;


        /// <summary>
        /// Create a CustomVM resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public CustomVM(string name, CustomVMArgs? args = null, CustomResourceOptions? options = null)
            : base("LnVps:index:CustomVM", name, args ?? new CustomVMArgs(), MakeResourceOptions(options, ""))
        {
        }

        private CustomVM(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("LnVps:index:CustomVM", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing CustomVM resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static CustomVM Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new CustomVM(name, id, options);
        }
    }

    public sealed class CustomVMArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Number of CPU cores
        /// </summary>
        [Input("cpu")]
        public Input<int>? Cpu { get; set; }

        /// <summary>
        /// Disk size in Gigabytes
        /// </summary>
        [Input("disk")]
        public Input<int>? Disk { get; set; }

        /// <summary>
        /// 'sata' | 'scsi' | 'pcie'
        /// </summary>
        [Input("disk_interface")]
        public Input<string>? DiskInterface { get; set; }

        /// <summary>
        /// Disk type (ssd or hdd)
        /// </summary>
        [Input("disk_type")]
        public Input<string>? DiskType { get; set; }

        /// <summary>
        /// VM image Id
        /// </summary>
        [Input("image_id")]
        public Input<Pulumi.LnVps.ImageId>? ImageId { get; set; }

        /// <summary>
        /// Memory in Gigabytes
        /// </summary>
        [Input("memory")]
        public Input<int>? Memory { get; set; }

        /// <summary>
        /// VM region Id
        /// </summary>
        [Input("region_id")]
        public Input<Pulumi.LnVps.RegionId>? RegionId { get; set; }

        /// <summary>
        /// ID of SSH key installed on VM.
        /// </summary>
        [Input("ssh_key_id")]
        public Input<string>? SshKeyId { get; set; }

        public CustomVMArgs()
        {
            DiskInterface = "pcie";
            DiskType = "ssd";
        }
        public static new CustomVMArgs Empty => new CustomVMArgs();
    }
}
