// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.ComponentModel;
using Pulumi;

namespace Pulumi.LnVps
{
    public enum ImageId
    {
        Ubuntu2404 = 1,
    }

    public enum RegionId
    {
        Dublin = 1,
        Quebec = 2,
        London = 3,
    }

    public enum TemplateId
    {
        /// <summary>
        /// 1 CPU, 1GB RAM, 40GB SSD, Dublin, 2.7 EUR/month
        /// </summary>
        Tiny = 13,
        /// <summary>
        /// 2 CPU, 2GB RAM, 80GB SSD, Dublin, 5.1 EUR/month
        /// </summary>
        Small = 14,
        /// <summary>
        /// 4 CPU, 4GB RAM, 160GB SSD, Dublin, 9.9 EUR/month
        /// </summary>
        Medium = 15,
    }
}
