// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.ComponentModel;
using Pulumi;

namespace Pulumi.Lnvps
{
    [EnumType]
    public readonly struct DiskInterface : IEquatable<DiskInterface>
    {
        private readonly string _value;

        private DiskInterface(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static DiskInterface Sata { get; } = new DiskInterface("sata");
        public static DiskInterface Scsi { get; } = new DiskInterface("scsi");
        public static DiskInterface Pcie { get; } = new DiskInterface("pcie");

        public static bool operator ==(DiskInterface left, DiskInterface right) => left.Equals(right);
        public static bool operator !=(DiskInterface left, DiskInterface right) => !left.Equals(right);

        public static explicit operator string(DiskInterface value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is DiskInterface other && Equals(other);
        public bool Equals(DiskInterface other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }

    [EnumType]
    public readonly struct DiskType : IEquatable<DiskType>
    {
        private readonly string _value;

        private DiskType(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static DiskType Ssd { get; } = new DiskType("ssd");
        public static DiskType Hdd { get; } = new DiskType("hdd");

        public static bool operator ==(DiskType left, DiskType right) => left.Equals(right);
        public static bool operator !=(DiskType left, DiskType right) => !left.Equals(right);

        public static explicit operator string(DiskType value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is DiskType other && Equals(other);
        public bool Equals(DiskType other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }

    public enum ImageId
    {
        Ubuntu2404 = 1,
    }

    public enum RegionId
    {
        Dublin = 1,
        Quebec = 2,
        London = 3,
    }

    public enum TemplateId
    {
        /// <summary>
        /// 1 CPU, 1GB RAM, 40GB SSD, Dublin, 2.7 EUR/month
        /// </summary>
        Tiny = 13,
        /// <summary>
        /// 2 CPU, 2GB RAM, 80GB SSD, Dublin, 5.1 EUR/month
        /// </summary>
        Small = 14,
        /// <summary>
        /// 4 CPU, 4GB RAM, 160GB SSD, Dublin, 9.9 EUR/month
        /// </summary>
        Medium = 15,
    }
}
