// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Lnvps
{
    [LnvpsResourceType("lnvps:index:IpAssignment")]
    public partial class IpAssignment : global::Pulumi.CustomResource
    {
        /// <summary>
        /// IP address with CIDR notation.
        /// </summary>
        [Output("ip")]
        public Output<string?> Ip { get; private set; } = null!;


        /// <summary>
        /// Create a IpAssignment resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public IpAssignment(string name, IpAssignmentArgs? args = null, CustomResourceOptions? options = null)
            : base("lnvps:index:IpAssignment", name, args ?? new IpAssignmentArgs(), MakeResourceOptions(options, ""))
        {
        }

        private IpAssignment(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("lnvps:index:IpAssignment", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing IpAssignment resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static IpAssignment Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new IpAssignment(name, id, options);
        }
    }

    public sealed class IpAssignmentArgs : global::Pulumi.ResourceArgs
    {
        public IpAssignmentArgs()
        {
        }
        public static new IpAssignmentArgs Empty => new IpAssignmentArgs();
    }
}
