// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Lnvps
{
    [LnvpsResourceType("lnvps:index:VM")]
    public partial class VM : global::Pulumi.CustomResource
    {
        /// <summary>
        /// VM IP addresses.
        /// </summary>
        [Output("ip_assignments")]
        public Output<ImmutableArray<string>> Ip_assignments { get; private set; } = null!;

        /// <summary>
        /// ID of SSH key installed on VM.
        /// </summary>
        [Output("ssh_key_id")]
        public Output<string?> Ssh_key_id { get; private set; } = null!;

        /// <summary>
        /// VM status.
        /// </summary>
        [Output("status")]
        public Output<string?> Status { get; private set; } = null!;


        /// <summary>
        /// Create a VM resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public VM(string name, VMArgs? args = null, CustomResourceOptions? options = null)
            : base("lnvps:index:VM", name, args ?? new VMArgs(), MakeResourceOptions(options, ""))
        {
        }

        private VM(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("lnvps:index:VM", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing VM resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static VM Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new VM(name, id, options);
        }
    }

    public sealed class VMArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// VM image Id
        /// </summary>
        [Input("image_id")]
        public Input<double>? Image_id { get; set; }

        /// <summary>
        /// ID of SSH key installed on VM.
        /// </summary>
        [Input("ssh_key_id")]
        public Input<string>? Ssh_key_id { get; set; }

        /// <summary>
        /// VM template Id
        /// </summary>
        [Input("template_id")]
        public Input<double>? Template_id { get; set; }

        public VMArgs()
        {
        }
        public static new VMArgs Empty => new VMArgs();
    }
}
